<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_Install_Admin extends CI_Migration
{
	public function up()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 10,
				'unsigned' => TRUE,
				'auto_increment' => TRUE
			),
			'user' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'password' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'power' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
				'default' => 'standart',
			),
		));
		$this->dbforge->add_key('id', TRUE);
		$this->dbforge->create_table('users');
		
		// Default değerlerin girileceği fonksiyonu çalıştırır
        $this->insert_default();
	}

	public function down()
	{
		$this->dbforge->drop_table('users');
	}

	public function insert_default()
	{
		$data = array(
			'user' => "root",
			'password' => md5("egegen"),
			'power' => "root"
		);
		
		$this->db->insert('users', $data);
		
		// Language migrationunu çalıştırır
        $this->up_language();
	}
	
	public function up_language()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 10,
				'unsigned' => TRUE,
				'auto_increment' => TRUE
			),
			'lang' => array(
				'type' => 'VARCHAR',
				'constraint' => '5',
			),
			'language' => array(
				'type' => 'VARCHAR',
				'constraint' => '100',
			),
			'default' => array(
				'type' => 'INT',
				'constraint' => 1,
				'default' => 0,
			),
		));
		$this->dbforge->add_key('id', TRUE);
		$this->dbforge->create_table('language');
		
		// Default değerlerin girileceği fonksiyonu çalıştırır
        $this->insert_default_language();
	}
	
	public function down_language()
	{
		$this->dbforge->drop_table('language');
	}

	public function insert_default_language()
	{
		$data = array(
			'lang' => "tr",
			'language' => "Türkçe",
			'default' => 1
		);
		
		$this->db->insert('language', $data);
		
		// Settings migrationunu çalıştırır
        $this->up_settings();
	}
	
	public function up_settings()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 10,
				'unsigned' => TRUE,
				'auto_increment' => TRUE
			),
			'title' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'logo' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'logo2' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'description' => array(
				'type' => 'TEXT',
			),
			'keywords' => array(
				'type' => 'TEXT',
			),
			'google_analytics' => array(
				'type' => 'TEXT',
			),
			'yandex_metrica' => array(
				'type' => 'TEXT',
			),
			'smtp_host' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'smtp_port' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'smtp_user' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'smtp_pass' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'smtp_to' => array(
				'type' => 'TEXT',
			),
			'social_facebook_url' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'social_instagram_url' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'social_twitter_url' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'social_youtube_url' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'social_googleplus_url' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'social_linkedin_url' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'social_pinterest_url' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'footer_text' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'search_module' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'page_cache' => array(
				'type' => 'INT',
				'constraint' => 1,
			),
			'css_js_cache' => array(
				'type' => 'INT',
				'constraint' => 1,
			),
			'lang' => array(
				'type' => 'VARCHAR',
				'constraint' => '5',
			)
		));
		$this->dbforge->add_key('id', TRUE);
		$this->dbforge->create_table('settings');
		
		// Default değerlerin girileceği fonksiyonu çalıştırır
        $this->insert_default_settings();
	}
	
	public function down_settings()
	{
		$this->dbforge->drop_table('settings');
	}

	public function insert_default_settings()
	{
		$data = array(
			'title' 		=> "Egegen CMS",
			'smtp_host' 	=> "mail.egegeninternet.com",
			'smtp_port' 	=> "587",
			'smtp_user' 	=> "smtp@egegeninternet.com",
			'smtp_pass' 	=> "SmTp:4528+",
			'smtp_to'		=> "noreply@egegeninternet.com",
			'footer_text'	=> "&copy; Egegen",
			'lang'			=> "tr"
		);
		
		$this->db->insert('settings', $data);
		
		// Routes migrationunu çalıştırır
        $this->up_routes();
	}
	
	public function up_routes()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 10,
				'unsigned' => TRUE,
				'auto_increment' => TRUE
			),
			'real_url' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'seo_url' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'lang' => array(
				'type' => 'VARCHAR',
				'constraint' => '5',
			)
		));
		$this->dbforge->add_key('id', TRUE);
		$this->dbforge->create_table('routes');
		
		// Page migrationunu çalıştırır
        $this->up_pages();
	}
	
	public function down_routes()
	{
		$this->dbforge->drop_table('routes');
	}
	
	public function up_pages()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 10,
				'unsigned' => TRUE,
				'auto_increment' => TRUE
			),
			'module' => array(
				'type' => 'VARCHAR',
				'constraint' => '100',
			),
			'lang_id' => array(
				'type' => 'VARCHAR',
				'constraint' => '100',
			),
			'title' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'header_img' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
				'null' => TRUE,
			),
			'list_img' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
				'null' => TRUE,
			),
			'summary' => array(
				'type' => 'TEXT',
			),
			'content' => array(
				'type' => 'TEXT',
			),
			'extra' => array(
				'type' => 'TEXT',
			),
			'description' => array(
				'type' => 'TEXT',
			),
			'keywords' => array(
				'type' => 'TEXT',
			),
			'updated_date' => array(
				'type' => 'DATETIME',
				'null' => TRUE,
			),
			'lang' => array(
				'type' => 'VARCHAR',
				'constraint' => '5',
			)
		));
		$this->dbforge->add_key('id', TRUE);
		$this->dbforge->create_table('page');
		
		// Static lang migrationunu çalıştırır
        $this->up_static_lang();
	}
	
	public function down_pages()
	{
		$this->dbforge->drop_table('page');
	}
	
	public function up_static_lang()
	{
		$this->dbforge->add_field(array(
			'id' => array(
				'type' => 'INT',
				'constraint' => 10,
				'unsigned' => TRUE,
				'auto_increment' => TRUE
			),
			'name' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			),
			'values' => array(
				'type' => 'TEXT',
			)
		));
		$this->dbforge->add_key('id', TRUE);
		$this->dbforge->create_table('static_lang');
		
		// City migrationunu çalıştırır
        $this->up_city();
	}
	
	public function down_static_lang()
	{
		$this->dbforge->drop_table('static_lang');
	}

	public function up_city()
	{
		$this->dbforge->add_field(array(
			'city_id' => array(
				'type' => 'INT',
				'constraint' => 10,
				'unsigned' => TRUE,
				'auto_increment' => TRUE
			),
			'title' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			)
		));
		$this->dbforge->add_key('city_id', TRUE);
		$this->dbforge->create_table('city');
		
        $this->insert_default_city();
	}

	public function insert_default_city()
	{
		$city = array(
			array('city_id' => '1','title' => 'Adana'),
			array('city_id' => '2','title' => 'Adıyaman'),
			array('city_id' => '3','title' => 'Afyon'),
			array('city_id' => '4','title' => 'Ağrı'),
			array('city_id' => '5','title' => 'Amasya'),
			array('city_id' => '6','title' => 'Ankara'),
			array('city_id' => '7','title' => 'Antalya'),
			array('city_id' => '8','title' => 'Artvin'),
			array('city_id' => '9','title' => 'Aydın'),
			array('city_id' => '10','title' => 'Balıkesir'),
			array('city_id' => '11','title' => 'Bilecik'),
			array('city_id' => '12','title' => 'Bingöl'),
			array('city_id' => '13','title' => 'Bitlis'),
			array('city_id' => '14','title' => 'Bolu'),
			array('city_id' => '15','title' => 'Burdur'),
			array('city_id' => '16','title' => 'Bursa'),
			array('city_id' => '17','title' => 'Çanakkale'),
			array('city_id' => '18','title' => 'Çankırı'),
			array('city_id' => '19','title' => 'Çorum'),
			array('city_id' => '20','title' => 'Denizli'),
			array('city_id' => '21','title' => 'Diyarbakır'),
			array('city_id' => '22','title' => 'Edirne'),
			array('city_id' => '23','title' => 'Elazığ'),
			array('city_id' => '24','title' => 'Erzincan'),
			array('city_id' => '25','title' => 'Erzurum'),
			array('city_id' => '26','title' => 'Eskişehir'),
			array('city_id' => '27','title' => 'Gaziantep'),
			array('city_id' => '28','title' => 'Giresun'),
			array('city_id' => '29','title' => 'Gümüşhane'),
			array('city_id' => '30','title' => 'Hakkari'),
			array('city_id' => '31','title' => 'Hatay'),
			array('city_id' => '32','title' => 'Isparta'),
			array('city_id' => '33','title' => 'İçel'),
			array('city_id' => '34','title' => 'İstanbul'),
			array('city_id' => '35','title' => 'İzmir'),
			array('city_id' => '36','title' => 'Kars'),
			array('city_id' => '37','title' => 'Kastamonu'),
			array('city_id' => '38','title' => 'Kayseri'),
			array('city_id' => '39','title' => 'Kırklareli'),
			array('city_id' => '40','title' => 'Kırşehir'),
			array('city_id' => '41','title' => 'Kocaeli'),
			array('city_id' => '42','title' => 'Konya'),
			array('city_id' => '43','title' => 'Kütahya'),
			array('city_id' => '44','title' => 'Malatya'),
			array('city_id' => '45','title' => 'Manisa'),
			array('city_id' => '46','title' => 'Kahramanmaraş'),
			array('city_id' => '47','title' => 'Mardin'),
			array('city_id' => '48','title' => 'Muğla'),
			array('city_id' => '49','title' => 'Muş'),
			array('city_id' => '50','title' => 'Nevşehir'),
			array('city_id' => '51','title' => 'Niğde'),
			array('city_id' => '52','title' => 'Ordu'),
			array('city_id' => '53','title' => 'Rize'),
			array('city_id' => '54','title' => 'Sakarya'),
			array('city_id' => '55','title' => 'Samsun'),
			array('city_id' => '56','title' => 'Siirt'),
			array('city_id' => '57','title' => 'Sinop'),
			array('city_id' => '58','title' => 'Sivas'),
			array('city_id' => '59','title' => 'Tekirdağ'),
			array('city_id' => '60','title' => 'Tokat'),
			array('city_id' => '61','title' => 'Trabzon'),
			array('city_id' => '62','title' => 'Tunceli'),
			array('city_id' => '63','title' => 'Şanlıurfa'),
			array('city_id' => '64','title' => 'Uşak'),
			array('city_id' => '65','title' => 'Van'),
			array('city_id' => '66','title' => 'Yozgat'),
			array('city_id' => '67','title' => 'Zonguldak'),
			array('city_id' => '68','title' => 'Aksaray'),
			array('city_id' => '69','title' => 'Bayburt'),
			array('city_id' => '70','title' => 'Karaman'),
			array('city_id' => '71','title' => 'Kırıkkale'),
			array('city_id' => '72','title' => 'Batman'),
			array('city_id' => '73','title' => 'Şırnak'),
			array('city_id' => '74','title' => 'Bartın'),
			array('city_id' => '75','title' => 'Ardahan'),
			array('city_id' => '76','title' => 'Iğdır'),
			array('city_id' => '77','title' => 'Yalova'),
			array('city_id' => '78','title' => 'Karabük'),
			array('city_id' => '79','title' => 'Kilis'),
			array('city_id' => '80','title' => 'Osmaniye'),
			array('city_id' => '81','title' => 'Düzce'),
			array('city_id' => '82','title' => 'Kıbrıs')
		  );
		$this->db->insert_batch('city', $city);
        $this->up_town();
	}

	public function up_town()
	{
		$this->dbforge->add_field(array(
			'town_id' => array(
				'type' => 'INT',
				'constraint' => 10,
				'unsigned' => TRUE,
				'auto_increment' => TRUE
			),
			'city_id' => array(
				'type' => 'INT',
				'constraint' => 10,
			),
			'title' => array(
				'type' => 'VARCHAR',
				'constraint' => '255',
			)
		));
		$this->dbforge->add_key('town_id', TRUE);
		$this->dbforge->create_table('town');
		
        $this->insert_default_town();
	}

	public function insert_default_town()
	{
		$town = array(
			array('town_id' => '1','city_id' => '1','title' => 'Merkez'),
			array('town_id' => '2','city_id' => '1','title' => 'Seyhan'),
			array('town_id' => '3','city_id' => '1','title' => 'Ceyhan'),
			array('town_id' => '4','city_id' => '1','title' => 'Feke'),
			array('town_id' => '5','city_id' => '1','title' => 'Karaisalı'),
			array('town_id' => '6','city_id' => '1','title' => 'Karataş'),
			array('town_id' => '7','city_id' => '1','title' => 'Kozan'),
			array('town_id' => '8','city_id' => '1','title' => 'Pozantı'),
			array('town_id' => '9','city_id' => '1','title' => 'Saimbeyli'),
			array('town_id' => '10','city_id' => '1','title' => 'Tufanbeyli'),
			array('town_id' => '11','city_id' => '1','title' => 'Yumurtalık'),
			array('town_id' => '12','city_id' => '1','title' => 'Yüreğir'),
			array('town_id' => '13','city_id' => '1','title' => 'Aladağ'),
			array('town_id' => '14','city_id' => '1','title' => 'İmamoğlu'),
			array('town_id' => '15','city_id' => '1','title' => 'Sarıçam'),
			array('town_id' => '16','city_id' => '1','title' => 'Çukurova'),
			array('town_id' => '17','city_id' => '2','title' => 'Merkez'),
			array('town_id' => '18','city_id' => '2','title' => 'Besni'),
			array('town_id' => '19','city_id' => '2','title' => 'Çelikhan'),
			array('town_id' => '20','city_id' => '2','title' => 'Gerger'),
			array('town_id' => '21','city_id' => '2','title' => 'Gölbaşı'),
			array('town_id' => '22','city_id' => '2','title' => 'Kahta'),
			array('town_id' => '23','city_id' => '2','title' => 'Samsat'),
			array('town_id' => '24','city_id' => '2','title' => 'Sincik'),
			array('town_id' => '25','city_id' => '2','title' => 'Tut'),
			array('town_id' => '26','city_id' => '3','title' => 'Merkez'),
			array('town_id' => '27','city_id' => '3','title' => 'Bolvadin'),
			array('town_id' => '28','city_id' => '3','title' => 'Çay'),
			array('town_id' => '29','city_id' => '3','title' => 'Dazkırı'),
			array('town_id' => '30','city_id' => '3','title' => 'Dinar'),
			array('town_id' => '31','city_id' => '3','title' => 'Emirdağ'),
			array('town_id' => '32','city_id' => '3','title' => 'İhsaniye'),
			array('town_id' => '33','city_id' => '3','title' => 'Sandıklı'),
			array('town_id' => '34','city_id' => '3','title' => 'Sinanpaşa'),
			array('town_id' => '35','city_id' => '3','title' => 'Sultandağı'),
			array('town_id' => '36','city_id' => '3','title' => 'Şuhut'),
			array('town_id' => '37','city_id' => '3','title' => 'Başmakçı'),
			array('town_id' => '38','city_id' => '3','title' => 'Bayat'),
			array('town_id' => '39','city_id' => '3','title' => 'İscehisar'),
			array('town_id' => '40','city_id' => '3','title' => 'Çobanlar'),
			array('town_id' => '41','city_id' => '3','title' => 'Evciler'),
			array('town_id' => '42','city_id' => '3','title' => 'Hocalar'),
			array('town_id' => '43','city_id' => '3','title' => 'Kızılören'),
			array('town_id' => '44','city_id' => '4','title' => 'Merkez'),
			array('town_id' => '45','city_id' => '4','title' => 'Diyadin'),
			array('town_id' => '46','city_id' => '4','title' => 'Doğubayazıt'),
			array('town_id' => '47','city_id' => '4','title' => 'Eleşkirt'),
			array('town_id' => '48','city_id' => '4','title' => 'Hamur'),
			array('town_id' => '49','city_id' => '4','title' => 'Patnos'),
			array('town_id' => '50','city_id' => '4','title' => 'Taşlıçay'),
			array('town_id' => '51','city_id' => '4','title' => 'Tutak'),
			array('town_id' => '52','city_id' => '5','title' => 'Merkez'),
			array('town_id' => '53','city_id' => '5','title' => 'Göynücek'),
			array('town_id' => '54','city_id' => '5','title' => 'Gümüşhacıköy'),
			array('town_id' => '55','city_id' => '5','title' => 'Merzifon'),
			array('town_id' => '56','city_id' => '5','title' => 'Suluova'),
			array('town_id' => '57','city_id' => '5','title' => 'Taşova'),
			array('town_id' => '58','city_id' => '5','title' => 'Hamamözü'),
			array('town_id' => '59','city_id' => '6','title' => 'Merkez'),
			array('town_id' => '60','city_id' => '6','title' => 'Altındağ'),
			array('town_id' => '61','city_id' => '6','title' => 'Ayaş'),
			array('town_id' => '62','city_id' => '6','title' => 'Bala'),
			array('town_id' => '63','city_id' => '6','title' => 'Beypazarı'),
			array('town_id' => '64','city_id' => '6','title' => 'Çamlıdere'),
			array('town_id' => '65','city_id' => '6','title' => 'Çankaya'),
			array('town_id' => '66','city_id' => '6','title' => 'Çubuk'),
			array('town_id' => '67','city_id' => '6','title' => 'Elmadağ'),
			array('town_id' => '68','city_id' => '6','title' => 'Güdül'),
			array('town_id' => '69','city_id' => '6','title' => 'Haymana'),
			array('town_id' => '70','city_id' => '6','title' => 'Kalecik'),
			array('town_id' => '71','city_id' => '6','title' => 'Kızılcahamam'),
			array('town_id' => '72','city_id' => '6','title' => 'Nallıhan'),
			array('town_id' => '73','city_id' => '6','title' => 'Polatlı'),
			array('town_id' => '74','city_id' => '6','title' => 'Şereflikoçhisar'),
			array('town_id' => '75','city_id' => '6','title' => 'Yenimahalle'),
			array('town_id' => '76','city_id' => '6','title' => 'Gölbaşı'),
			array('town_id' => '77','city_id' => '6','title' => 'Keçiören'),
			array('town_id' => '78','city_id' => '6','title' => 'Mamak'),
			array('town_id' => '79','city_id' => '6','title' => 'Sincan'),
			array('town_id' => '80','city_id' => '6','title' => 'Kazan'),
			array('town_id' => '81','city_id' => '6','title' => 'Akyurt'),
			array('town_id' => '82','city_id' => '6','title' => 'Etimesgut'),
			array('town_id' => '83','city_id' => '6','title' => 'Evren'),
			array('town_id' => '84','city_id' => '6','title' => 'Pursaklar'),
			array('town_id' => '85','city_id' => '7','title' => 'Merkez'),
			array('town_id' => '86','city_id' => '7','title' => 'Akseki'),
			array('town_id' => '87','city_id' => '7','title' => 'Alanya'),
			array('town_id' => '88','city_id' => '7','title' => 'Elmalı'),
			array('town_id' => '89','city_id' => '7','title' => 'Finike'),
			array('town_id' => '90','city_id' => '7','title' => 'Gazipaşa'),
			array('town_id' => '91','city_id' => '7','title' => 'Gündoğmuş'),
			array('town_id' => '92','city_id' => '7','title' => 'Kaş'),
			array('town_id' => '93','city_id' => '7','title' => 'Korkuteli'),
			array('town_id' => '94','city_id' => '7','title' => 'Kumluca'),
			array('town_id' => '95','city_id' => '7','title' => 'Manavgat'),
			array('town_id' => '96','city_id' => '7','title' => 'Serik'),
			array('town_id' => '97','city_id' => '7','title' => 'Demre'),
			array('town_id' => '98','city_id' => '7','title' => 'İbradı'),
			array('town_id' => '99','city_id' => '7','title' => 'Kemer'),
			array('town_id' => '100','city_id' => '7','title' => 'Aksu'),
			array('town_id' => '101','city_id' => '7','title' => 'Döşemealtı'),
			array('town_id' => '102','city_id' => '7','title' => 'Kepez'),
			array('town_id' => '103','city_id' => '7','title' => 'Konyaaltı'),
			array('town_id' => '104','city_id' => '7','title' => 'Muratpaşa'),
			array('town_id' => '105','city_id' => '8','title' => 'Ardanuç'),
			array('town_id' => '106','city_id' => '8','title' => 'Arhavi'),
			array('town_id' => '107','city_id' => '8','title' => 'Merkez'),
			array('town_id' => '108','city_id' => '8','title' => 'Borçka'),
			array('town_id' => '109','city_id' => '8','title' => 'Hopa'),
			array('town_id' => '110','city_id' => '8','title' => 'Şavşat'),
			array('town_id' => '111','city_id' => '8','title' => 'Yusufeli'),
			array('town_id' => '112','city_id' => '8','title' => 'Murgul'),
			array('town_id' => '113','city_id' => '9','title' => 'Merkez'),
			array('town_id' => '114','city_id' => '9','title' => 'Bozdoğan'),
			array('town_id' => '115','city_id' => '9','title' => 'Çine'),
			array('town_id' => '116','city_id' => '9','title' => 'Germencik'),
			array('town_id' => '117','city_id' => '9','title' => 'Karacasu'),
			array('town_id' => '118','city_id' => '9','title' => 'Koçarlı'),
			array('town_id' => '119','city_id' => '9','title' => 'Kuşadası'),
			array('town_id' => '120','city_id' => '9','title' => 'Kuyucak'),
			array('town_id' => '121','city_id' => '9','title' => 'Nazilli'),
			array('town_id' => '122','city_id' => '9','title' => 'Söke'),
			array('town_id' => '123','city_id' => '9','title' => 'Sultanhisar'),
			array('town_id' => '124','city_id' => '9','title' => 'Yenipazar'),
			array('town_id' => '125','city_id' => '9','title' => 'Buharkent'),
			array('town_id' => '126','city_id' => '9','title' => 'İncirliova'),
			array('town_id' => '127','city_id' => '9','title' => 'Karpuzlu'),
			array('town_id' => '128','city_id' => '9','title' => 'Köşk'),
			array('town_id' => '129','city_id' => '9','title' => 'Didim'),
			array('town_id' => '130','city_id' => '9','title' => 'Efeler'),
			array('town_id' => '131','city_id' => '10','title' => 'Merkez'),
			array('town_id' => '132','city_id' => '10','title' => 'Ayvalık'),
			array('town_id' => '133','city_id' => '10','title' => 'Balya'),
			array('town_id' => '134','city_id' => '10','title' => 'Bandırma'),
			array('town_id' => '135','city_id' => '10','title' => 'Bigadiç'),
			array('town_id' => '136','city_id' => '10','title' => 'Burhaniye'),
			array('town_id' => '137','city_id' => '10','title' => 'Dursunbey'),
			array('town_id' => '138','city_id' => '10','title' => 'Edremit'),
			array('town_id' => '139','city_id' => '10','title' => 'Erdek'),
			array('town_id' => '140','city_id' => '10','title' => 'Gönen'),
			array('town_id' => '141','city_id' => '10','title' => 'Havran'),
			array('town_id' => '142','city_id' => '10','title' => 'İvrindi'),
			array('town_id' => '143','city_id' => '10','title' => 'Kepsut'),
			array('town_id' => '144','city_id' => '10','title' => 'Manyas'),
			array('town_id' => '145','city_id' => '10','title' => 'Savaştepe'),
			array('town_id' => '146','city_id' => '10','title' => 'Sındırgı'),
			array('town_id' => '147','city_id' => '10','title' => 'Susurluk'),
			array('town_id' => '148','city_id' => '10','title' => 'Marmara'),
			array('town_id' => '149','city_id' => '10','title' => 'Gömeç'),
			array('town_id' => '150','city_id' => '10','title' => 'Altıeylül'),
			array('town_id' => '151','city_id' => '10','title' => 'Karesi'),
			array('town_id' => '152','city_id' => '11','title' => 'Merkez'),
			array('town_id' => '153','city_id' => '11','title' => 'Bozüyük'),
			array('town_id' => '154','city_id' => '11','title' => 'Gölpazarı'),
			array('town_id' => '155','city_id' => '11','title' => 'Osmaneli'),
			array('town_id' => '156','city_id' => '11','title' => 'Pazaryeri'),
			array('town_id' => '157','city_id' => '11','title' => 'Söğüt'),
			array('town_id' => '158','city_id' => '11','title' => 'Yenipazar'),
			array('town_id' => '159','city_id' => '11','title' => 'İnhisar'),
			array('town_id' => '160','city_id' => '12','title' => 'Merkez'),
			array('town_id' => '161','city_id' => '12','title' => 'Genç'),
			array('town_id' => '162','city_id' => '12','title' => 'Karlıova'),
			array('town_id' => '163','city_id' => '12','title' => 'Kiğı'),
			array('town_id' => '164','city_id' => '12','title' => 'Solhan'),
			array('town_id' => '165','city_id' => '12','title' => 'Adaklı'),
			array('town_id' => '166','city_id' => '12','title' => 'Yayladere'),
			array('town_id' => '167','city_id' => '12','title' => 'Yedisu'),
			array('town_id' => '168','city_id' => '13','title' => 'Adilcevaz'),
			array('town_id' => '169','city_id' => '13','title' => 'Ahlat'),
			array('town_id' => '170','city_id' => '13','title' => 'Merkez'),
			array('town_id' => '171','city_id' => '13','title' => 'Hizan'),
			array('town_id' => '172','city_id' => '13','title' => 'Mutki'),
			array('town_id' => '173','city_id' => '13','title' => 'Tatvan'),
			array('town_id' => '174','city_id' => '13','title' => 'Güroymak'),
			array('town_id' => '175','city_id' => '14','title' => 'Merkez'),
			array('town_id' => '176','city_id' => '14','title' => 'Gerede'),
			array('town_id' => '177','city_id' => '14','title' => 'Göynük'),
			array('town_id' => '178','city_id' => '14','title' => 'Kıbrıscık'),
			array('town_id' => '179','city_id' => '14','title' => 'Mengen'),
			array('town_id' => '180','city_id' => '14','title' => 'Mudurnu'),
			array('town_id' => '181','city_id' => '14','title' => 'Seben'),
			array('town_id' => '182','city_id' => '14','title' => 'Dörtdivan'),
			array('town_id' => '183','city_id' => '14','title' => 'Yeniçağa'),
			array('town_id' => '184','city_id' => '15','title' => 'Ağlasun'),
			array('town_id' => '185','city_id' => '15','title' => 'Bucak'),
			array('town_id' => '186','city_id' => '15','title' => 'Merkez'),
			array('town_id' => '187','city_id' => '15','title' => 'Gölhisar'),
			array('town_id' => '188','city_id' => '15','title' => 'Tefenni'),
			array('town_id' => '189','city_id' => '15','title' => 'Yeşilova'),
			array('town_id' => '190','city_id' => '15','title' => 'Karamanlı'),
			array('town_id' => '191','city_id' => '15','title' => 'Kemer'),
			array('town_id' => '192','city_id' => '15','title' => 'Altınyayla'),
			array('town_id' => '193','city_id' => '15','title' => 'Çavdır'),
			array('town_id' => '194','city_id' => '15','title' => 'Çeltikçi'),
			array('town_id' => '195','city_id' => '16','title' => 'Merkez'),
			array('town_id' => '196','city_id' => '16','title' => 'Gemlik'),
			array('town_id' => '197','city_id' => '16','title' => 'İnegöl'),
			array('town_id' => '198','city_id' => '16','title' => 'İznik'),
			array('town_id' => '199','city_id' => '16','title' => 'Karacabey'),
			array('town_id' => '200','city_id' => '16','title' => 'Keles'),
			array('town_id' => '201','city_id' => '16','title' => 'Mudanya'),
			array('town_id' => '202','city_id' => '16','title' => 'Mustafakemalpaşa'),
			array('town_id' => '203','city_id' => '16','title' => 'Orhaneli'),
			array('town_id' => '204','city_id' => '16','title' => 'Orhangazi'),
			array('town_id' => '205','city_id' => '16','title' => 'Yenişehir'),
			array('town_id' => '206','city_id' => '16','title' => 'Büyükorhan'),
			array('town_id' => '207','city_id' => '16','title' => 'Harmancık'),
			array('town_id' => '208','city_id' => '16','title' => 'Nilüfer'),
			array('town_id' => '209','city_id' => '16','title' => 'Osmangazi'),
			array('town_id' => '210','city_id' => '16','title' => 'Yıldırım'),
			array('town_id' => '211','city_id' => '16','title' => 'Gürsu'),
			array('town_id' => '212','city_id' => '16','title' => 'Kestel'),
			array('town_id' => '213','city_id' => '17','title' => 'Ayvacık'),
			array('town_id' => '214','city_id' => '17','title' => 'Bayramiç'),
			array('town_id' => '215','city_id' => '17','title' => 'Biga'),
			array('town_id' => '216','city_id' => '17','title' => 'Bozcaada'),
			array('town_id' => '217','city_id' => '17','title' => 'Çan'),
			array('town_id' => '218','city_id' => '17','title' => 'Merkez'),
			array('town_id' => '219','city_id' => '17','title' => 'Eceabat'),
			array('town_id' => '220','city_id' => '17','title' => 'Ezine'),
			array('town_id' => '221','city_id' => '17','title' => 'Gelibolu'),
			array('town_id' => '222','city_id' => '17','title' => 'Gökçeada'),
			array('town_id' => '223','city_id' => '17','title' => 'Lapseki'),
			array('town_id' => '224','city_id' => '17','title' => 'Yenice'),
			array('town_id' => '225','city_id' => '18','title' => 'Merkez'),
			array('town_id' => '226','city_id' => '18','title' => 'Çerkeş'),
			array('town_id' => '227','city_id' => '18','title' => 'Eldivan'),
			array('town_id' => '228','city_id' => '18','title' => 'Ilgaz'),
			array('town_id' => '229','city_id' => '18','title' => 'Kurşunlu'),
			array('town_id' => '230','city_id' => '18','title' => 'Orta'),
			array('town_id' => '231','city_id' => '18','title' => 'Şabanözü'),
			array('town_id' => '232','city_id' => '18','title' => 'Yapraklı'),
			array('town_id' => '233','city_id' => '18','title' => 'Atkaracalar'),
			array('town_id' => '234','city_id' => '18','title' => 'Kızılırmak'),
			array('town_id' => '235','city_id' => '18','title' => 'Bayramören'),
			array('town_id' => '236','city_id' => '18','title' => 'Korgun'),
			array('town_id' => '237','city_id' => '19','title' => 'Alaca'),
			array('town_id' => '238','city_id' => '19','title' => 'Bayat'),
			array('town_id' => '239','city_id' => '19','title' => 'Merkez'),
			array('town_id' => '240','city_id' => '19','title' => 'İskilip'),
			array('town_id' => '241','city_id' => '19','title' => 'Kargı'),
			array('town_id' => '242','city_id' => '19','title' => 'Mecitözü'),
			array('town_id' => '243','city_id' => '19','title' => 'Ortaköy'),
			array('town_id' => '244','city_id' => '19','title' => 'Osmancık'),
			array('town_id' => '245','city_id' => '19','title' => 'Sungurlu'),
			array('town_id' => '246','city_id' => '19','title' => 'Boğazkale'),
			array('town_id' => '247','city_id' => '19','title' => 'Uğurludağ'),
			array('town_id' => '248','city_id' => '19','title' => 'Dodurga'),
			array('town_id' => '249','city_id' => '19','title' => 'Laçin'),
			array('town_id' => '250','city_id' => '19','title' => 'Oğuzlar'),
			array('town_id' => '251','city_id' => '20','title' => 'Merkez'),
			array('town_id' => '252','city_id' => '20','title' => 'Acıpayam'),
			array('town_id' => '253','city_id' => '20','title' => 'Buldan'),
			array('town_id' => '254','city_id' => '20','title' => 'Çal'),
			array('town_id' => '255','city_id' => '20','title' => 'Çameli'),
			array('town_id' => '256','city_id' => '20','title' => 'Çardak'),
			array('town_id' => '257','city_id' => '20','title' => 'Çivril'),
			array('town_id' => '258','city_id' => '20','title' => 'Güney'),
			array('town_id' => '259','city_id' => '20','title' => 'Kale'),
			array('town_id' => '260','city_id' => '20','title' => 'Sarayköy'),
			array('town_id' => '261','city_id' => '20','title' => 'Tavas'),
			array('town_id' => '262','city_id' => '20','title' => 'Babadağ'),
			array('town_id' => '263','city_id' => '20','title' => 'Bekilli'),
			array('town_id' => '264','city_id' => '20','title' => 'Honaz'),
			array('town_id' => '265','city_id' => '20','title' => 'Serinhisar'),
			array('town_id' => '266','city_id' => '20','title' => 'Pamukkale'),
			array('town_id' => '267','city_id' => '20','title' => 'Baklan'),
			array('town_id' => '268','city_id' => '20','title' => 'Beyağaç'),
			array('town_id' => '269','city_id' => '20','title' => 'Bozkurt'),
			array('town_id' => '270','city_id' => '20','title' => 'Merkezefendi'),
			array('town_id' => '271','city_id' => '21','title' => 'Merkez'),
			array('town_id' => '272','city_id' => '21','title' => 'Bismil'),
			array('town_id' => '273','city_id' => '21','title' => 'Çermik'),
			array('town_id' => '274','city_id' => '21','title' => 'Çınar'),
			array('town_id' => '275','city_id' => '21','title' => 'Çüngüş'),
			array('town_id' => '276','city_id' => '21','title' => 'Dicle'),
			array('town_id' => '277','city_id' => '21','title' => 'Ergani'),
			array('town_id' => '278','city_id' => '21','title' => 'Hani'),
			array('town_id' => '279','city_id' => '21','title' => 'Hazro'),
			array('town_id' => '280','city_id' => '21','title' => 'Kulp'),
			array('town_id' => '281','city_id' => '21','title' => 'Lice'),
			array('town_id' => '282','city_id' => '21','title' => 'Silvan'),
			array('town_id' => '283','city_id' => '21','title' => 'Eğil'),
			array('town_id' => '284','city_id' => '21','title' => 'Kocaköy'),
			array('town_id' => '285','city_id' => '21','title' => 'Bağlar'),
			array('town_id' => '286','city_id' => '21','title' => 'Kayapınar'),
			array('town_id' => '287','city_id' => '21','title' => 'Sur'),
			array('town_id' => '288','city_id' => '21','title' => 'Yenişehir'),
			array('town_id' => '289','city_id' => '22','title' => 'Merkez'),
			array('town_id' => '290','city_id' => '22','title' => 'Enez'),
			array('town_id' => '291','city_id' => '22','title' => 'Havsa'),
			array('town_id' => '292','city_id' => '22','title' => 'İpsala'),
			array('town_id' => '293','city_id' => '22','title' => 'Keşan'),
			array('town_id' => '294','city_id' => '22','title' => 'Lalapaşa'),
			array('town_id' => '295','city_id' => '22','title' => 'Meriç'),
			array('town_id' => '296','city_id' => '22','title' => 'Uzunköprü'),
			array('town_id' => '297','city_id' => '22','title' => 'Süloğlu'),
			array('town_id' => '298','city_id' => '23','title' => 'Ağın'),
			array('town_id' => '299','city_id' => '23','title' => 'Baskil'),
			array('town_id' => '300','city_id' => '23','title' => 'Merkez'),
			array('town_id' => '301','city_id' => '23','title' => 'Karakoçan'),
			array('town_id' => '302','city_id' => '23','title' => 'Keban'),
			array('town_id' => '303','city_id' => '23','title' => 'Maden'),
			array('town_id' => '304','city_id' => '23','title' => 'Palu'),
			array('town_id' => '305','city_id' => '23','title' => 'Sivrice'),
			array('town_id' => '306','city_id' => '23','title' => 'Arıcak'),
			array('town_id' => '307','city_id' => '23','title' => 'Kovancılar'),
			array('town_id' => '308','city_id' => '23','title' => 'Alacakaya'),
			array('town_id' => '309','city_id' => '24','title' => 'Çayırlı'),
			array('town_id' => '310','city_id' => '24','title' => 'Merkez'),
			array('town_id' => '311','city_id' => '24','title' => 'İliç'),
			array('town_id' => '312','city_id' => '24','title' => 'Kemah'),
			array('town_id' => '313','city_id' => '24','title' => 'Kemaliye'),
			array('town_id' => '314','city_id' => '24','title' => 'Refahiye'),
			array('town_id' => '315','city_id' => '24','title' => 'Tercan'),
			array('town_id' => '316','city_id' => '24','title' => 'Üzümlü'),
			array('town_id' => '317','city_id' => '24','title' => 'Otlukbeli'),
			array('town_id' => '318','city_id' => '25','title' => 'Merkez'),
			array('town_id' => '319','city_id' => '25','title' => 'Aşkale'),
			array('town_id' => '320','city_id' => '25','title' => 'Çat'),
			array('town_id' => '321','city_id' => '25','title' => 'Hınıs'),
			array('town_id' => '322','city_id' => '25','title' => 'Horasan'),
			array('town_id' => '323','city_id' => '25','title' => 'İspir'),
			array('town_id' => '324','city_id' => '25','title' => 'Karayazı'),
			array('town_id' => '325','city_id' => '25','title' => 'Narman'),
			array('town_id' => '326','city_id' => '25','title' => 'Oltu'),
			array('town_id' => '327','city_id' => '25','title' => 'Olur'),
			array('town_id' => '328','city_id' => '25','title' => 'Pasinler'),
			array('town_id' => '329','city_id' => '25','title' => 'Şenkaya'),
			array('town_id' => '330','city_id' => '25','title' => 'Tekman'),
			array('town_id' => '331','city_id' => '25','title' => 'Tortum'),
			array('town_id' => '332','city_id' => '25','title' => 'Karaçoban'),
			array('town_id' => '333','city_id' => '25','title' => 'Uzundere'),
			array('town_id' => '334','city_id' => '25','title' => 'Pazaryolu'),
			array('town_id' => '335','city_id' => '25','title' => 'Aziziye'),
			array('town_id' => '336','city_id' => '25','title' => 'Köprüköy'),
			array('town_id' => '337','city_id' => '25','title' => 'Palandöken'),
			array('town_id' => '338','city_id' => '25','title' => 'Yakutiye'),
			array('town_id' => '339','city_id' => '26','title' => 'Merkez'),
			array('town_id' => '340','city_id' => '26','title' => 'Çifteler'),
			array('town_id' => '341','city_id' => '26','title' => 'Mahmudiye'),
			array('town_id' => '342','city_id' => '26','title' => 'Mihalıççık'),
			array('town_id' => '343','city_id' => '26','title' => 'Sarıcakaya'),
			array('town_id' => '344','city_id' => '26','title' => 'Seyitgazi'),
			array('town_id' => '345','city_id' => '26','title' => 'Sivrihisar'),
			array('town_id' => '346','city_id' => '26','title' => 'Alpu'),
			array('town_id' => '347','city_id' => '26','title' => 'Beylikova'),
			array('town_id' => '348','city_id' => '26','title' => 'İnönü'),
			array('town_id' => '349','city_id' => '26','title' => 'Günyüzü'),
			array('town_id' => '350','city_id' => '26','title' => 'Han'),
			array('town_id' => '351','city_id' => '26','title' => 'Mihalgazi'),
			array('town_id' => '352','city_id' => '26','title' => 'Odunpazarı'),
			array('town_id' => '353','city_id' => '26','title' => 'Tepebaşı'),
			array('town_id' => '354','city_id' => '27','title' => 'Merkez'),
			array('town_id' => '355','city_id' => '27','title' => 'Araban'),
			array('town_id' => '356','city_id' => '27','title' => 'İslahiye'),
			array('town_id' => '357','city_id' => '27','title' => 'Nizip'),
			array('town_id' => '358','city_id' => '27','title' => 'Oğuzeli'),
			array('town_id' => '359','city_id' => '27','title' => 'Yavuzeli'),
			array('town_id' => '360','city_id' => '27','title' => 'Şahinbey'),
			array('town_id' => '361','city_id' => '27','title' => 'Şehitkamil'),
			array('town_id' => '362','city_id' => '27','title' => 'Karkamış'),
			array('town_id' => '363','city_id' => '27','title' => 'Nurdağı'),
			array('town_id' => '364','city_id' => '28','title' => 'Alucra'),
			array('town_id' => '365','city_id' => '28','title' => 'Bulancak'),
			array('town_id' => '366','city_id' => '28','title' => 'Dereli'),
			array('town_id' => '367','city_id' => '28','title' => 'Espiye'),
			array('town_id' => '368','city_id' => '28','title' => 'Eynesil'),
			array('town_id' => '369','city_id' => '28','title' => 'Merkez'),
			array('town_id' => '370','city_id' => '28','title' => 'Görele'),
			array('town_id' => '371','city_id' => '28','title' => 'Keşap'),
			array('town_id' => '372','city_id' => '28','title' => 'Şebinkarahisar'),
			array('town_id' => '373','city_id' => '28','title' => 'Tirebolu'),
			array('town_id' => '374','city_id' => '28','title' => 'Piraziz'),
			array('town_id' => '375','city_id' => '28','title' => 'Yağlıdere'),
			array('town_id' => '376','city_id' => '28','title' => 'Çamoluk'),
			array('town_id' => '377','city_id' => '28','title' => 'Çanakçı'),
			array('town_id' => '378','city_id' => '28','title' => 'Doğankent'),
			array('town_id' => '379','city_id' => '28','title' => 'Güce'),
			array('town_id' => '380','city_id' => '29','title' => 'Merkez'),
			array('town_id' => '381','city_id' => '29','title' => 'Kelkit'),
			array('town_id' => '382','city_id' => '29','title' => 'Şiran'),
			array('town_id' => '383','city_id' => '29','title' => 'Torul'),
			array('town_id' => '384','city_id' => '29','title' => 'Köse'),
			array('town_id' => '385','city_id' => '29','title' => 'Kürtün'),
			array('town_id' => '386','city_id' => '30','title' => 'Çukurca'),
			array('town_id' => '387','city_id' => '30','title' => 'Merkez'),
			array('town_id' => '388','city_id' => '30','title' => 'Şemdinli'),
			array('town_id' => '389','city_id' => '30','title' => 'Yüksekova'),
			array('town_id' => '390','city_id' => '31','title' => 'Altınözü'),
			array('town_id' => '391','city_id' => '31','title' => 'Dörtyol'),
			array('town_id' => '392','city_id' => '31','title' => 'Merkez'),
			array('town_id' => '393','city_id' => '31','title' => 'Hassa'),
			array('town_id' => '394','city_id' => '31','title' => 'İskenderun'),
			array('town_id' => '395','city_id' => '31','title' => 'Kırıkhan'),
			array('town_id' => '396','city_id' => '31','title' => 'Reyhanlı'),
			array('town_id' => '397','city_id' => '31','title' => 'Samandağ'),
			array('town_id' => '398','city_id' => '31','title' => 'Yayladağı'),
			array('town_id' => '399','city_id' => '31','title' => 'Erzin'),
			array('town_id' => '400','city_id' => '31','title' => 'Belen'),
			array('town_id' => '401','city_id' => '31','title' => 'Kumlu'),
			array('town_id' => '402','city_id' => '31','title' => 'Antakya'),
			array('town_id' => '403','city_id' => '31','title' => 'Arsuz'),
			array('town_id' => '404','city_id' => '31','title' => 'Defne'),
			array('town_id' => '405','city_id' => '31','title' => 'Payas'),
			array('town_id' => '406','city_id' => '32','title' => 'Atabey'),
			array('town_id' => '407','city_id' => '32','title' => 'Eğirdir'),
			array('town_id' => '408','city_id' => '32','title' => 'Gelendost'),
			array('town_id' => '409','city_id' => '32','title' => 'Merkez'),
			array('town_id' => '410','city_id' => '32','title' => 'Keçiborlu'),
			array('town_id' => '411','city_id' => '32','title' => 'Senirkent'),
			array('town_id' => '412','city_id' => '32','title' => 'Sütçüler'),
			array('town_id' => '413','city_id' => '32','title' => 'Şarkikaraağaç'),
			array('town_id' => '414','city_id' => '32','title' => 'Uluborlu'),
			array('town_id' => '415','city_id' => '32','title' => 'Yalvaç'),
			array('town_id' => '416','city_id' => '32','title' => 'Aksu / Isparta'),
			array('town_id' => '417','city_id' => '32','title' => 'Gönen / Isparta'),
			array('town_id' => '418','city_id' => '32','title' => 'Yenişarbademli'),
			array('town_id' => '419','city_id' => '33','title' => 'Merkez'),
			array('town_id' => '420','city_id' => '33','title' => 'Anamur'),
			array('town_id' => '421','city_id' => '33','title' => 'Erdemli'),
			array('town_id' => '422','city_id' => '33','title' => 'Gülnar'),
			array('town_id' => '423','city_id' => '33','title' => 'Mut'),
			array('town_id' => '424','city_id' => '33','title' => 'Silifke'),
			array('town_id' => '425','city_id' => '33','title' => 'Tarsus'),
			array('town_id' => '426','city_id' => '33','title' => 'Aydıncık'),
			array('town_id' => '427','city_id' => '33','title' => 'Bozyazı'),
			array('town_id' => '428','city_id' => '33','title' => 'Çamlıyayla'),
			array('town_id' => '429','city_id' => '33','title' => 'Akdeniz'),
			array('town_id' => '430','city_id' => '33','title' => 'Mezitli'),
			array('town_id' => '431','city_id' => '33','title' => 'Toroslar'),
			array('town_id' => '432','city_id' => '33','title' => 'Yenişehir'),
			array('town_id' => '433','city_id' => '34','title' => 'Merkez'),
			array('town_id' => '434','city_id' => '34','title' => 'Adalar'),
			array('town_id' => '435','city_id' => '34','title' => 'Bakırköy'),
			array('town_id' => '436','city_id' => '34','title' => 'Beşiktaş'),
			array('town_id' => '437','city_id' => '34','title' => 'Beykoz'),
			array('town_id' => '438','city_id' => '34','title' => 'Beyoğlu'),
			array('town_id' => '439','city_id' => '34','title' => 'Çatalca'),
			array('town_id' => '440','city_id' => '34','title' => 'Eyüp'),
			array('town_id' => '441','city_id' => '34','title' => 'Fatih'),
			array('town_id' => '442','city_id' => '34','title' => 'Gaziosmanpaşa'),
			array('town_id' => '443','city_id' => '34','title' => 'Kadıköy'),
			array('town_id' => '444','city_id' => '34','title' => 'Kartal'),
			array('town_id' => '445','city_id' => '34','title' => 'Sarıyer'),
			array('town_id' => '446','city_id' => '34','title' => 'Silivri'),
			array('town_id' => '447','city_id' => '34','title' => 'Şile'),
			array('town_id' => '448','city_id' => '34','title' => 'Şişli'),
			array('town_id' => '449','city_id' => '34','title' => 'Üsküdar'),
			array('town_id' => '450','city_id' => '34','title' => 'Zeytinburnu'),
			array('town_id' => '451','city_id' => '34','title' => 'Büyükçekmece'),
			array('town_id' => '452','city_id' => '34','title' => 'Kağıthane'),
			array('town_id' => '453','city_id' => '34','title' => 'Küçükçekmece'),
			array('town_id' => '454','city_id' => '34','title' => 'Pendik'),
			array('town_id' => '455','city_id' => '34','title' => 'Ümraniye'),
			array('town_id' => '456','city_id' => '34','title' => 'Bayrampaşa'),
			array('town_id' => '457','city_id' => '34','title' => 'Avcılar'),
			array('town_id' => '458','city_id' => '34','title' => 'Bağcılar'),
			array('town_id' => '459','city_id' => '34','title' => 'Bahçelievler'),
			array('town_id' => '460','city_id' => '34','title' => 'Güngören'),
			array('town_id' => '461','city_id' => '34','title' => 'Maltepe'),
			array('town_id' => '462','city_id' => '34','title' => 'Sultanbeyli'),
			array('town_id' => '463','city_id' => '34','title' => 'Tuzla'),
			array('town_id' => '464','city_id' => '34','title' => 'Esenler'),
			array('town_id' => '465','city_id' => '34','title' => 'Arnavutköy'),
			array('town_id' => '466','city_id' => '34','title' => 'Ataşehir'),
			array('town_id' => '467','city_id' => '34','title' => 'Başakşehir'),
			array('town_id' => '468','city_id' => '34','title' => 'Beylikdüzü'),
			array('town_id' => '469','city_id' => '34','title' => 'Çekmeköy'),
			array('town_id' => '470','city_id' => '34','title' => 'Esenyurt'),
			array('town_id' => '471','city_id' => '34','title' => 'Sancaktepe'),
			array('town_id' => '472','city_id' => '34','title' => 'Sultangazi'),
			array('town_id' => '473','city_id' => '35','title' => 'Merkez'),
			array('town_id' => '474','city_id' => '35','title' => 'Aliağa'),
			array('town_id' => '475','city_id' => '35','title' => 'Bayındır'),
			array('town_id' => '476','city_id' => '35','title' => 'Bergama'),
			array('town_id' => '477','city_id' => '35','title' => 'Bornova'),
			array('town_id' => '478','city_id' => '35','title' => 'Çeşme'),
			array('town_id' => '479','city_id' => '35','title' => 'Dikili'),
			array('town_id' => '480','city_id' => '35','title' => 'Foça'),
			array('town_id' => '481','city_id' => '35','title' => 'Karaburun'),
			array('town_id' => '482','city_id' => '35','title' => 'Karşıyaka'),
			array('town_id' => '483','city_id' => '35','title' => 'Kemalpaşa'),
			array('town_id' => '484','city_id' => '35','title' => 'Kınık'),
			array('town_id' => '485','city_id' => '35','title' => 'Kiraz'),
			array('town_id' => '486','city_id' => '35','title' => 'Menemen'),
			array('town_id' => '487','city_id' => '35','title' => 'Ödemiş'),
			array('town_id' => '488','city_id' => '35','title' => 'Seferihisar'),
			array('town_id' => '489','city_id' => '35','title' => 'Selçuk'),
			array('town_id' => '490','city_id' => '35','title' => 'Tire'),
			array('town_id' => '491','city_id' => '35','title' => 'Torbalı'),
			array('town_id' => '492','city_id' => '35','title' => 'Urla'),
			array('town_id' => '493','city_id' => '35','title' => 'Beydağ'),
			array('town_id' => '494','city_id' => '35','title' => 'Buca'),
			array('town_id' => '495','city_id' => '35','title' => 'Konak'),
			array('town_id' => '496','city_id' => '35','title' => 'Menderes'),
			array('town_id' => '497','city_id' => '35','title' => 'Balçova'),
			array('town_id' => '498','city_id' => '35','title' => 'Çiğli'),
			array('town_id' => '499','city_id' => '35','title' => 'Gaziemir'),
			array('town_id' => '500','city_id' => '35','title' => 'Narlıdere'),
			array('town_id' => '501','city_id' => '35','title' => 'Güzelbahçe'),
			array('town_id' => '502','city_id' => '35','title' => 'Bayraklı'),
			array('town_id' => '503','city_id' => '35','title' => 'Karabağlar'),
			array('town_id' => '504','city_id' => '36','title' => 'Arpaçay'),
			array('town_id' => '505','city_id' => '36','title' => 'Digor'),
			array('town_id' => '506','city_id' => '36','title' => 'Kağızman'),
			array('town_id' => '507','city_id' => '36','title' => 'Merkez'),
			array('town_id' => '508','city_id' => '36','title' => 'Sarıkamış'),
			array('town_id' => '509','city_id' => '36','title' => 'Selim'),
			array('town_id' => '510','city_id' => '36','title' => 'Susuz'),
			array('town_id' => '511','city_id' => '36','title' => 'Akyaka'),
			array('town_id' => '512','city_id' => '37','title' => 'Abana'),
			array('town_id' => '513','city_id' => '37','title' => 'Araç'),
			array('town_id' => '514','city_id' => '37','title' => 'Azdavay'),
			array('town_id' => '515','city_id' => '37','title' => 'Bozkurt'),
			array('town_id' => '516','city_id' => '37','title' => 'Cide'),
			array('town_id' => '517','city_id' => '37','title' => 'Çatalzeytin'),
			array('town_id' => '518','city_id' => '37','title' => 'Daday'),
			array('town_id' => '519','city_id' => '37','title' => 'Devrekani'),
			array('town_id' => '520','city_id' => '37','title' => 'İnebolu'),
			array('town_id' => '521','city_id' => '37','title' => 'Merkez'),
			array('town_id' => '522','city_id' => '37','title' => 'Küre'),
			array('town_id' => '523','city_id' => '37','title' => 'Taşköprü'),
			array('town_id' => '524','city_id' => '37','title' => 'Tosya'),
			array('town_id' => '525','city_id' => '37','title' => 'İhsangazi'),
			array('town_id' => '526','city_id' => '37','title' => 'Pınarbaşı'),
			array('town_id' => '527','city_id' => '37','title' => 'Şenpazar'),
			array('town_id' => '528','city_id' => '37','title' => 'Ağlı'),
			array('town_id' => '529','city_id' => '37','title' => 'Doğanyurt'),
			array('town_id' => '530','city_id' => '37','title' => 'Hanönü'),
			array('town_id' => '531','city_id' => '37','title' => 'Seydiler'),
			array('town_id' => '532','city_id' => '38','title' => 'Merkez'),
			array('town_id' => '533','city_id' => '38','title' => 'Bünyan'),
			array('town_id' => '534','city_id' => '38','title' => 'Develi'),
			array('town_id' => '535','city_id' => '38','title' => 'Felahiye'),
			array('town_id' => '536','city_id' => '38','title' => 'İncesu'),
			array('town_id' => '537','city_id' => '38','title' => 'Pınarbaşı'),
			array('town_id' => '538','city_id' => '38','title' => 'Sarıoğlan'),
			array('town_id' => '539','city_id' => '38','title' => 'Sarız'),
			array('town_id' => '540','city_id' => '38','title' => 'Tomarza'),
			array('town_id' => '541','city_id' => '38','title' => 'Yahyalı'),
			array('town_id' => '542','city_id' => '38','title' => 'Yeşilhisar'),
			array('town_id' => '543','city_id' => '38','title' => 'Akkışla'),
			array('town_id' => '544','city_id' => '38','title' => 'Talas'),
			array('town_id' => '545','city_id' => '38','title' => 'Kocasinan'),
			array('town_id' => '546','city_id' => '38','title' => 'Melikgazi'),
			array('town_id' => '547','city_id' => '38','title' => 'Hacılar'),
			array('town_id' => '548','city_id' => '38','title' => 'Özvatan'),
			array('town_id' => '549','city_id' => '39','title' => 'Babaeski'),
			array('town_id' => '550','city_id' => '39','title' => 'Demirköy'),
			array('town_id' => '551','city_id' => '39','title' => 'Merkez'),
			array('town_id' => '552','city_id' => '39','title' => 'Kofçaz'),
			array('town_id' => '553','city_id' => '39','title' => 'Lüleburgaz'),
			array('town_id' => '554','city_id' => '39','title' => 'Pehlivanköy'),
			array('town_id' => '555','city_id' => '39','title' => 'Pınarhisar'),
			array('town_id' => '556','city_id' => '39','title' => 'Vize'),
			array('town_id' => '557','city_id' => '40','title' => 'Çiçekdağı'),
			array('town_id' => '558','city_id' => '40','title' => 'Kaman'),
			array('town_id' => '559','city_id' => '40','title' => 'Merkez'),
			array('town_id' => '560','city_id' => '40','title' => 'Mucur'),
			array('town_id' => '561','city_id' => '40','title' => 'Akpınar'),
			array('town_id' => '562','city_id' => '40','title' => 'Akçakent'),
			array('town_id' => '563','city_id' => '40','title' => 'Boztepe'),
			array('town_id' => '564','city_id' => '41','title' => 'Merkez'),
			array('town_id' => '565','city_id' => '41','title' => 'Gebze'),
			array('town_id' => '566','city_id' => '41','title' => 'Gölcük'),
			array('town_id' => '567','city_id' => '41','title' => 'Kandıra'),
			array('town_id' => '568','city_id' => '41','title' => 'Karamürsel'),
			array('town_id' => '569','city_id' => '41','title' => 'Körfez'),
			array('town_id' => '570','city_id' => '41','title' => 'Derince'),
			array('town_id' => '571','city_id' => '41','title' => 'Başiskele'),
			array('town_id' => '572','city_id' => '41','title' => 'Çayırova'),
			array('town_id' => '573','city_id' => '41','title' => 'Darıca'),
			array('town_id' => '574','city_id' => '41','title' => 'Dilovası'),
			array('town_id' => '575','city_id' => '41','title' => 'İzmit'),
			array('town_id' => '576','city_id' => '41','title' => 'Kartepe'),
			array('town_id' => '577','city_id' => '42','title' => 'Merkez'),
			array('town_id' => '578','city_id' => '42','title' => 'Akşehir'),
			array('town_id' => '579','city_id' => '42','title' => 'Beyşehir'),
			array('town_id' => '580','city_id' => '42','title' => 'Bozkır'),
			array('town_id' => '581','city_id' => '42','title' => 'Cihanbeyli'),
			array('town_id' => '582','city_id' => '42','title' => 'Çumra'),
			array('town_id' => '583','city_id' => '42','title' => 'Doğanhisar'),
			array('town_id' => '584','city_id' => '42','title' => 'Ereğli'),
			array('town_id' => '585','city_id' => '42','title' => 'Hadim'),
			array('town_id' => '586','city_id' => '42','title' => 'Ilgın'),
			array('town_id' => '587','city_id' => '42','title' => 'Kadınhanı'),
			array('town_id' => '588','city_id' => '42','title' => 'Karapınar'),
			array('town_id' => '589','city_id' => '42','title' => 'Kulu'),
			array('town_id' => '590','city_id' => '42','title' => 'Sarayönü'),
			array('town_id' => '591','city_id' => '42','title' => 'Seydişehir'),
			array('town_id' => '592','city_id' => '42','title' => 'Yunak'),
			array('town_id' => '593','city_id' => '42','title' => 'Akören'),
			array('town_id' => '594','city_id' => '42','title' => 'Altınekin'),
			array('town_id' => '595','city_id' => '42','title' => 'Derebucak'),
			array('town_id' => '596','city_id' => '42','title' => 'Hüyük'),
			array('town_id' => '597','city_id' => '42','title' => 'Karatay'),
			array('town_id' => '598','city_id' => '42','title' => 'Meram'),
			array('town_id' => '599','city_id' => '42','title' => 'Selçuklu'),
			array('town_id' => '600','city_id' => '42','title' => 'Taşkent'),
			array('town_id' => '601','city_id' => '42','title' => 'Ahırlı'),
			array('town_id' => '602','city_id' => '42','title' => 'Çeltik'),
			array('town_id' => '603','city_id' => '42','title' => 'Derbent'),
			array('town_id' => '604','city_id' => '42','title' => 'Emirgazi'),
			array('town_id' => '605','city_id' => '42','title' => 'Güneysınır'),
			array('town_id' => '606','city_id' => '42','title' => 'Halkapınar'),
			array('town_id' => '607','city_id' => '42','title' => 'Tuzlukçu'),
			array('town_id' => '608','city_id' => '42','title' => 'Yalıhüyük'),
			array('town_id' => '609','city_id' => '43','title' => 'Altıntaş'),
			array('town_id' => '610','city_id' => '43','title' => 'Domaniç'),
			array('town_id' => '611','city_id' => '43','title' => 'Emet'),
			array('town_id' => '612','city_id' => '43','title' => 'Gediz'),
			array('town_id' => '613','city_id' => '43','title' => 'Merkez'),
			array('town_id' => '614','city_id' => '43','title' => 'Simav'),
			array('town_id' => '615','city_id' => '43','title' => 'Tavşanlı'),
			array('town_id' => '616','city_id' => '43','title' => 'Aslanapa'),
			array('town_id' => '617','city_id' => '43','title' => 'Dumlupınar'),
			array('town_id' => '618','city_id' => '43','title' => 'Hisarcık'),
			array('town_id' => '619','city_id' => '43','title' => 'Şaphane'),
			array('town_id' => '620','city_id' => '43','title' => 'Çavdarhisar'),
			array('town_id' => '621','city_id' => '43','title' => 'Pazarlar'),
			array('town_id' => '622','city_id' => '44','title' => 'Merkez'),
			array('town_id' => '623','city_id' => '44','title' => 'Akçadağ'),
			array('town_id' => '624','city_id' => '44','title' => 'Arapgir'),
			array('town_id' => '625','city_id' => '44','title' => 'Arguvan'),
			array('town_id' => '626','city_id' => '44','title' => 'Darende'),
			array('town_id' => '627','city_id' => '44','title' => 'Doğanşehir'),
			array('town_id' => '628','city_id' => '44','title' => 'Hekimhan'),
			array('town_id' => '629','city_id' => '44','title' => 'Pütürge'),
			array('town_id' => '630','city_id' => '44','title' => 'Yeşilyurt'),
			array('town_id' => '631','city_id' => '44','title' => 'Battalgazi'),
			array('town_id' => '632','city_id' => '44','title' => 'Doğanyol'),
			array('town_id' => '633','city_id' => '44','title' => 'Kale'),
			array('town_id' => '634','city_id' => '44','title' => 'Kuluncak'),
			array('town_id' => '635','city_id' => '44','title' => 'Yazıhan'),
			array('town_id' => '636','city_id' => '45','title' => 'Merkez'),
			array('town_id' => '637','city_id' => '45','title' => 'Akhisar'),
			array('town_id' => '638','city_id' => '45','title' => 'Alaşehir'),
			array('town_id' => '639','city_id' => '45','title' => 'Demirci'),
			array('town_id' => '640','city_id' => '45','title' => 'Gördes'),
			array('town_id' => '641','city_id' => '45','title' => 'Kırkağaç'),
			array('town_id' => '642','city_id' => '45','title' => 'Kula'),
			array('town_id' => '643','city_id' => '45','title' => 'Salihli'),
			array('town_id' => '644','city_id' => '45','title' => 'Sarıgöl'),
			array('town_id' => '645','city_id' => '45','title' => 'Saruhanlı'),
			array('town_id' => '646','city_id' => '45','title' => 'Selendi'),
			array('town_id' => '647','city_id' => '45','title' => 'Soma'),
			array('town_id' => '648','city_id' => '45','title' => 'Turgutlu'),
			array('town_id' => '649','city_id' => '45','title' => 'Ahmetli'),
			array('town_id' => '650','city_id' => '45','title' => 'Gölmarmara'),
			array('town_id' => '651','city_id' => '45','title' => 'Köprübaşı'),
			array('town_id' => '652','city_id' => '45','title' => 'Şehzadeler'),
			array('town_id' => '653','city_id' => '45','title' => 'Yunusemre'),
			array('town_id' => '654','city_id' => '46','title' => 'Merkez'),
			array('town_id' => '655','city_id' => '46','title' => 'Afşin'),
			array('town_id' => '656','city_id' => '46','title' => 'Andırın'),
			array('town_id' => '657','city_id' => '46','title' => 'Elbistan'),
			array('town_id' => '658','city_id' => '46','title' => 'Göksun'),
			array('town_id' => '659','city_id' => '46','title' => 'Pazarcık'),
			array('town_id' => '660','city_id' => '46','title' => 'Türkoğlu'),
			array('town_id' => '661','city_id' => '46','title' => 'Çağlayancerit'),
			array('town_id' => '662','city_id' => '46','title' => 'Ekinözü'),
			array('town_id' => '663','city_id' => '46','title' => 'Nurhak'),
			array('town_id' => '664','city_id' => '46','title' => 'Dulkadiroğlu'),
			array('town_id' => '665','city_id' => '46','title' => 'Onikişubat'),
			array('town_id' => '666','city_id' => '47','title' => 'Merkez'),
			array('town_id' => '667','city_id' => '47','title' => 'Derik'),
			array('town_id' => '668','city_id' => '47','title' => 'Kızıltepe'),
			array('town_id' => '669','city_id' => '47','title' => 'Mazıdağı'),
			array('town_id' => '670','city_id' => '47','title' => 'Midyat'),
			array('town_id' => '671','city_id' => '47','title' => 'Nusaybin'),
			array('town_id' => '672','city_id' => '47','title' => 'Ömerli'),
			array('town_id' => '673','city_id' => '47','title' => 'Savur'),
			array('town_id' => '674','city_id' => '47','title' => 'Dargeçit'),
			array('town_id' => '675','city_id' => '47','title' => 'Yeşilli'),
			array('town_id' => '676','city_id' => '47','title' => 'Artuklu'),
			array('town_id' => '677','city_id' => '48','title' => 'Merkez'),
			array('town_id' => '678','city_id' => '48','title' => 'Bodrum'),
			array('town_id' => '679','city_id' => '48','title' => 'Datça'),
			array('town_id' => '680','city_id' => '48','title' => 'Fethiye'),
			array('town_id' => '681','city_id' => '48','title' => 'Köyceğiz'),
			array('town_id' => '682','city_id' => '48','title' => 'Marmaris'),
			array('town_id' => '683','city_id' => '48','title' => 'Milas'),
			array('town_id' => '684','city_id' => '48','title' => 'Ula'),
			array('town_id' => '685','city_id' => '48','title' => 'Yatağan'),
			array('town_id' => '686','city_id' => '48','title' => 'Dalaman'),
			array('town_id' => '687','city_id' => '48','title' => 'Ortaca'),
			array('town_id' => '688','city_id' => '48','title' => 'Kavaklıdere'),
			array('town_id' => '689','city_id' => '48','title' => 'Menteşe'),
			array('town_id' => '690','city_id' => '48','title' => 'Seydikemer'),
			array('town_id' => '691','city_id' => '49','title' => 'Bulanık'),
			array('town_id' => '692','city_id' => '49','title' => 'Malazgirt'),
			array('town_id' => '693','city_id' => '49','title' => 'Merkez'),
			array('town_id' => '694','city_id' => '49','title' => 'Varto'),
			array('town_id' => '695','city_id' => '49','title' => 'Hasköy'),
			array('town_id' => '696','city_id' => '49','title' => 'Korkut'),
			array('town_id' => '697','city_id' => '50','title' => 'Avanos'),
			array('town_id' => '698','city_id' => '50','title' => 'Derinkuyu'),
			array('town_id' => '699','city_id' => '50','title' => 'Gülşehir'),
			array('town_id' => '700','city_id' => '50','title' => 'Hacıbektaş'),
			array('town_id' => '701','city_id' => '50','title' => 'Kozaklı'),
			array('town_id' => '702','city_id' => '50','title' => 'Merkez'),
			array('town_id' => '703','city_id' => '50','title' => 'Ürgüp'),
			array('town_id' => '704','city_id' => '50','title' => 'Acıgöl'),
			array('town_id' => '705','city_id' => '51','title' => 'Bor'),
			array('town_id' => '706','city_id' => '51','title' => 'Çamardı'),
			array('town_id' => '707','city_id' => '51','title' => 'Merkez'),
			array('town_id' => '708','city_id' => '51','title' => 'Ulukışla'),
			array('town_id' => '709','city_id' => '51','title' => 'Altunhisar'),
			array('town_id' => '710','city_id' => '51','title' => 'Çiftlik'),
			array('town_id' => '711','city_id' => '52','title' => 'Merkez'),
			array('town_id' => '712','city_id' => '52','title' => 'Akkuş'),
			array('town_id' => '713','city_id' => '52','title' => 'Aybastı'),
			array('town_id' => '714','city_id' => '52','title' => 'Fatsa'),
			array('town_id' => '715','city_id' => '52','title' => 'Gölköy'),
			array('town_id' => '716','city_id' => '52','title' => 'Korgan'),
			array('town_id' => '717','city_id' => '52','title' => 'Kumru'),
			array('town_id' => '718','city_id' => '52','title' => 'Mesudiye'),
			array('town_id' => '719','city_id' => '52','title' => 'Perşembe'),
			array('town_id' => '720','city_id' => '52','title' => 'Ulubey'),
			array('town_id' => '721','city_id' => '52','title' => 'Ünye'),
			array('town_id' => '722','city_id' => '52','title' => 'Gülyalı'),
			array('town_id' => '723','city_id' => '52','title' => 'Gürgentepe'),
			array('town_id' => '724','city_id' => '52','title' => 'Çamaş'),
			array('town_id' => '725','city_id' => '52','title' => 'Çatalpınar'),
			array('town_id' => '726','city_id' => '52','title' => 'Çaybaşı'),
			array('town_id' => '727','city_id' => '52','title' => 'İkizce'),
			array('town_id' => '728','city_id' => '52','title' => 'Kabadüz'),
			array('town_id' => '729','city_id' => '52','title' => 'Kabataş'),
			array('town_id' => '730','city_id' => '52','title' => 'Altınordu'),
			array('town_id' => '731','city_id' => '53','title' => 'Ardeşen'),
			array('town_id' => '732','city_id' => '53','title' => 'Çamlıhemşin'),
			array('town_id' => '733','city_id' => '53','title' => 'Çayeli'),
			array('town_id' => '734','city_id' => '53','title' => 'Fındıklı'),
			array('town_id' => '735','city_id' => '53','title' => 'İkizdere'),
			array('town_id' => '736','city_id' => '53','title' => 'Kalkandere'),
			array('town_id' => '737','city_id' => '53','title' => 'Pazar'),
			array('town_id' => '738','city_id' => '53','title' => 'Merkez'),
			array('town_id' => '739','city_id' => '53','title' => 'Güneysu'),
			array('town_id' => '740','city_id' => '53','title' => 'Derepazarı'),
			array('town_id' => '741','city_id' => '53','title' => 'Hemşin'),
			array('town_id' => '742','city_id' => '53','title' => 'İyidere'),
			array('town_id' => '743','city_id' => '54','title' => 'Merkez'),
			array('town_id' => '744','city_id' => '54','title' => 'Akyazı'),
			array('town_id' => '745','city_id' => '54','title' => 'Geyve'),
			array('town_id' => '746','city_id' => '54','title' => 'Hendek'),
			array('town_id' => '747','city_id' => '54','title' => 'Karasu'),
			array('town_id' => '748','city_id' => '54','title' => 'Kaynarca'),
			array('town_id' => '749','city_id' => '54','title' => 'Sapanca'),
			array('town_id' => '750','city_id' => '54','title' => 'Kocaali'),
			array('town_id' => '751','city_id' => '54','title' => 'Pamukova'),
			array('town_id' => '752','city_id' => '54','title' => 'Taraklı'),
			array('town_id' => '753','city_id' => '54','title' => 'Ferizli'),
			array('town_id' => '754','city_id' => '54','title' => 'Karapürçek'),
			array('town_id' => '755','city_id' => '54','title' => 'Söğütlü'),
			array('town_id' => '756','city_id' => '54','title' => 'Adapazarı'),
			array('town_id' => '757','city_id' => '54','title' => 'Arifiye'),
			array('town_id' => '758','city_id' => '54','title' => 'Erenler'),
			array('town_id' => '759','city_id' => '54','title' => 'Serdivan'),
			array('town_id' => '760','city_id' => '55','title' => 'Merkez'),
			array('town_id' => '761','city_id' => '55','title' => 'Alaçam'),
			array('town_id' => '762','city_id' => '55','title' => 'Bafra'),
			array('town_id' => '763','city_id' => '55','title' => 'Çarşamba'),
			array('town_id' => '764','city_id' => '55','title' => 'Havza'),
			array('town_id' => '765','city_id' => '55','title' => 'Kavak'),
			array('town_id' => '766','city_id' => '55','title' => 'Ladik'),
			array('town_id' => '767','city_id' => '55','title' => 'Terme'),
			array('town_id' => '768','city_id' => '55','title' => 'Vezirköprü'),
			array('town_id' => '769','city_id' => '55','title' => 'Asarcık'),
			array('town_id' => '770','city_id' => '55','title' => '19 Mayıs'),
			array('town_id' => '771','city_id' => '55','title' => 'Salıpazarı'),
			array('town_id' => '772','city_id' => '55','title' => 'Tekkeköy'),
			array('town_id' => '773','city_id' => '55','title' => 'Ayvacık'),
			array('town_id' => '774','city_id' => '55','title' => 'Yakakent'),
			array('town_id' => '775','city_id' => '55','title' => 'Atakum'),
			array('town_id' => '776','city_id' => '55','title' => 'Canik'),
			array('town_id' => '777','city_id' => '55','title' => 'İlkadım'),
			array('town_id' => '778','city_id' => '56','title' => 'Baykan'),
			array('town_id' => '779','city_id' => '56','title' => 'Eruh'),
			array('town_id' => '780','city_id' => '56','title' => 'Kurtalan'),
			array('town_id' => '781','city_id' => '56','title' => 'Pervari'),
			array('town_id' => '782','city_id' => '56','title' => 'Merkez'),
			array('town_id' => '783','city_id' => '56','title' => 'Şirvan'),
			array('town_id' => '784','city_id' => '56','title' => 'Tillo'),
			array('town_id' => '785','city_id' => '57','title' => 'Ayancık'),
			array('town_id' => '786','city_id' => '57','title' => 'Boyabat'),
			array('town_id' => '787','city_id' => '57','title' => 'Durağan'),
			array('town_id' => '788','city_id' => '57','title' => 'Erfelek'),
			array('town_id' => '789','city_id' => '57','title' => 'Gerze'),
			array('town_id' => '790','city_id' => '57','title' => 'Merkez'),
			array('town_id' => '791','city_id' => '57','title' => 'Türkeli'),
			array('town_id' => '792','city_id' => '57','title' => 'Dikmen'),
			array('town_id' => '793','city_id' => '57','title' => 'Saraydüzü'),
			array('town_id' => '794','city_id' => '58','title' => 'Divriği'),
			array('town_id' => '795','city_id' => '58','title' => 'Gemerek'),
			array('town_id' => '796','city_id' => '58','title' => 'Gürün'),
			array('town_id' => '797','city_id' => '58','title' => 'Hafik'),
			array('town_id' => '798','city_id' => '58','title' => 'İmranlı'),
			array('town_id' => '799','city_id' => '58','title' => 'Kangal'),
			array('town_id' => '800','city_id' => '58','title' => 'Koyulhisar'),
			array('town_id' => '801','city_id' => '58','title' => 'Merkez'),
			array('town_id' => '802','city_id' => '58','title' => 'Suşehri'),
			array('town_id' => '803','city_id' => '58','title' => 'Şarkışla'),
			array('town_id' => '804','city_id' => '58','title' => 'Yıldızeli'),
			array('town_id' => '805','city_id' => '58','title' => 'Zara'),
			array('town_id' => '806','city_id' => '58','title' => 'Akıncılar'),
			array('town_id' => '807','city_id' => '58','title' => 'Altınyayla'),
			array('town_id' => '808','city_id' => '58','title' => 'Doğanşar'),
			array('town_id' => '809','city_id' => '58','title' => 'Gölova'),
			array('town_id' => '810','city_id' => '58','title' => 'Ulaş'),
			array('town_id' => '811','city_id' => '59','title' => 'Merkez'),
			array('town_id' => '812','city_id' => '59','title' => 'Çerkezköy'),
			array('town_id' => '813','city_id' => '59','title' => 'Çorlu'),
			array('town_id' => '814','city_id' => '59','title' => 'Hayrabolu'),
			array('town_id' => '815','city_id' => '59','title' => 'Malkara'),
			array('town_id' => '816','city_id' => '59','title' => 'Muratlı'),
			array('town_id' => '817','city_id' => '59','title' => 'Saray'),
			array('town_id' => '818','city_id' => '59','title' => 'Şarköy'),
			array('town_id' => '819','city_id' => '59','title' => 'Marmaraereğlisi'),
			array('town_id' => '820','city_id' => '59','title' => 'Ergene'),
			array('town_id' => '821','city_id' => '59','title' => 'Süleymanpaşa'),
			array('town_id' => '822','city_id' => '60','title' => 'Almus'),
			array('town_id' => '823','city_id' => '60','title' => 'Artova'),
			array('town_id' => '824','city_id' => '60','title' => 'Erbaa'),
			array('town_id' => '825','city_id' => '60','title' => 'Niksar'),
			array('town_id' => '826','city_id' => '60','title' => 'Reşadiye'),
			array('town_id' => '827','city_id' => '60','title' => 'Merkez'),
			array('town_id' => '828','city_id' => '60','title' => 'Turhal'),
			array('town_id' => '829','city_id' => '60','title' => 'Zile'),
			array('town_id' => '830','city_id' => '60','title' => 'Pazar'),
			array('town_id' => '831','city_id' => '60','title' => 'Yeşilyurt'),
			array('town_id' => '832','city_id' => '60','title' => 'Başçiftlik'),
			array('town_id' => '833','city_id' => '60','title' => 'Sulusaray'),
			array('town_id' => '834','city_id' => '61','title' => 'Merkez'),
			array('town_id' => '835','city_id' => '61','title' => 'Akçaabat'),
			array('town_id' => '836','city_id' => '61','title' => 'Araklı'),
			array('town_id' => '837','city_id' => '61','title' => 'Arsin'),
			array('town_id' => '838','city_id' => '61','title' => 'Çaykara'),
			array('town_id' => '839','city_id' => '61','title' => 'Maçka'),
			array('town_id' => '840','city_id' => '61','title' => 'Of'),
			array('town_id' => '841','city_id' => '61','title' => 'Sürmene'),
			array('town_id' => '842','city_id' => '61','title' => 'Tonya'),
			array('town_id' => '843','city_id' => '61','title' => 'Vakfıkebir'),
			array('town_id' => '844','city_id' => '61','title' => 'Yomra'),
			array('town_id' => '845','city_id' => '61','title' => 'Beşikdüzü'),
			array('town_id' => '846','city_id' => '61','title' => 'Şalpazarı'),
			array('town_id' => '847','city_id' => '61','title' => 'Çarşıbaşı'),
			array('town_id' => '848','city_id' => '61','title' => 'Dernekpazarı'),
			array('town_id' => '849','city_id' => '61','title' => 'Düzköy'),
			array('town_id' => '850','city_id' => '61','title' => 'Hayrat'),
			array('town_id' => '851','city_id' => '61','title' => 'Köprübaşı'),
			array('town_id' => '852','city_id' => '61','title' => 'Ortahisar'),
			array('town_id' => '853','city_id' => '62','title' => 'Çemişgezek'),
			array('town_id' => '854','city_id' => '62','title' => 'Hozat'),
			array('town_id' => '855','city_id' => '62','title' => 'Mazgirt'),
			array('town_id' => '856','city_id' => '62','title' => 'Nazımiye'),
			array('town_id' => '857','city_id' => '62','title' => 'Ovacık'),
			array('town_id' => '858','city_id' => '62','title' => 'Pertek'),
			array('town_id' => '859','city_id' => '62','title' => 'Pülümür'),
			array('town_id' => '860','city_id' => '62','title' => 'Merkez'),
			array('town_id' => '861','city_id' => '63','title' => 'Merkez'),
			array('town_id' => '862','city_id' => '63','title' => 'Akçakale'),
			array('town_id' => '863','city_id' => '63','title' => 'Birecik'),
			array('town_id' => '864','city_id' => '63','title' => 'Bozova'),
			array('town_id' => '865','city_id' => '63','title' => 'Ceylanpınar'),
			array('town_id' => '866','city_id' => '63','title' => 'Halfeti'),
			array('town_id' => '867','city_id' => '63','title' => 'Hilvan'),
			array('town_id' => '868','city_id' => '63','title' => 'Siverek'),
			array('town_id' => '869','city_id' => '63','title' => 'Suruç'),
			array('town_id' => '870','city_id' => '63','title' => 'Viranşehir'),
			array('town_id' => '871','city_id' => '63','title' => 'Harran'),
			array('town_id' => '872','city_id' => '63','title' => 'Eyyübiye'),
			array('town_id' => '873','city_id' => '63','title' => 'Haliliye'),
			array('town_id' => '874','city_id' => '63','title' => 'Karaköprü'),
			array('town_id' => '875','city_id' => '64','title' => 'Banaz'),
			array('town_id' => '876','city_id' => '64','title' => 'Eşme'),
			array('town_id' => '877','city_id' => '64','title' => 'Karahallı'),
			array('town_id' => '878','city_id' => '64','title' => 'Sivaslı'),
			array('town_id' => '879','city_id' => '64','title' => 'Ulubey'),
			array('town_id' => '880','city_id' => '64','title' => 'Merkez'),
			array('town_id' => '881','city_id' => '65','title' => 'Merkez'),
			array('town_id' => '882','city_id' => '65','title' => 'Başkale'),
			array('town_id' => '883','city_id' => '65','title' => 'Çatak'),
			array('town_id' => '884','city_id' => '65','title' => 'Erciş'),
			array('town_id' => '885','city_id' => '65','title' => 'Gevaş'),
			array('town_id' => '886','city_id' => '65','title' => 'Gürpınar'),
			array('town_id' => '887','city_id' => '65','title' => 'Muradiye'),
			array('town_id' => '888','city_id' => '65','title' => 'Özalp'),
			array('town_id' => '889','city_id' => '65','title' => 'Bahçesaray'),
			array('town_id' => '890','city_id' => '65','title' => 'Çaldıran'),
			array('town_id' => '891','city_id' => '65','title' => 'Edremit'),
			array('town_id' => '892','city_id' => '65','title' => 'Saray'),
			array('town_id' => '893','city_id' => '65','title' => 'İpekyolu'),
			array('town_id' => '894','city_id' => '65','title' => 'Tuşba'),
			array('town_id' => '895','city_id' => '66','title' => 'Akdağmadeni'),
			array('town_id' => '896','city_id' => '66','title' => 'Boğazlıyan'),
			array('town_id' => '897','city_id' => '66','title' => 'Çayıralan'),
			array('town_id' => '898','city_id' => '66','title' => 'Çekerek'),
			array('town_id' => '899','city_id' => '66','title' => 'Sarıkaya'),
			array('town_id' => '900','city_id' => '66','title' => 'Sorgun'),
			array('town_id' => '901','city_id' => '66','title' => 'Şefaatli'),
			array('town_id' => '902','city_id' => '66','title' => 'Yerköy'),
			array('town_id' => '903','city_id' => '66','title' => 'Merkez'),
			array('town_id' => '904','city_id' => '66','title' => 'Aydıncık'),
			array('town_id' => '905','city_id' => '66','title' => 'Çandır'),
			array('town_id' => '906','city_id' => '66','title' => 'Kadışehri'),
			array('town_id' => '907','city_id' => '66','title' => 'Saraykent'),
			array('town_id' => '908','city_id' => '66','title' => 'Yenifakılı'),
			array('town_id' => '909','city_id' => '67','title' => 'Çaycuma'),
			array('town_id' => '910','city_id' => '67','title' => 'Devrek'),
			array('town_id' => '911','city_id' => '67','title' => 'Ereğli'),
			array('town_id' => '912','city_id' => '67','title' => 'Merkez'),
			array('town_id' => '913','city_id' => '67','title' => 'Alaplı'),
			array('town_id' => '914','city_id' => '67','title' => 'Gökçebey'),
			array('town_id' => '915','city_id' => '68','title' => 'Merkez'),
			array('town_id' => '916','city_id' => '68','title' => 'Ortaköy'),
			array('town_id' => '917','city_id' => '68','title' => 'Ağaçören'),
			array('town_id' => '918','city_id' => '68','title' => 'Güzelyurt'),
			array('town_id' => '919','city_id' => '68','title' => 'Sarıyahşi'),
			array('town_id' => '920','city_id' => '68','title' => 'Eskil'),
			array('town_id' => '921','city_id' => '68','title' => 'Gülağaç'),
			array('town_id' => '922','city_id' => '69','title' => 'Merkez'),
			array('town_id' => '923','city_id' => '69','title' => 'Aydıntepe'),
			array('town_id' => '924','city_id' => '69','title' => 'Demirözü'),
			array('town_id' => '925','city_id' => '70','title' => 'Ermenek'),
			array('town_id' => '926','city_id' => '70','title' => 'Merkez'),
			array('town_id' => '927','city_id' => '70','title' => 'Ayrancı'),
			array('town_id' => '928','city_id' => '70','title' => 'Kazımkarabekir'),
			array('town_id' => '929','city_id' => '70','title' => 'Başyayla'),
			array('town_id' => '930','city_id' => '70','title' => 'Sarıveliler'),
			array('town_id' => '931','city_id' => '71','title' => 'Delice'),
			array('town_id' => '932','city_id' => '71','title' => 'Keskin'),
			array('town_id' => '933','city_id' => '71','title' => 'Merkez'),
			array('town_id' => '934','city_id' => '71','title' => 'Sulakyurt'),
			array('town_id' => '935','city_id' => '71','title' => 'Bahşili'),
			array('town_id' => '936','city_id' => '71','title' => 'Balışeyh'),
			array('town_id' => '937','city_id' => '71','title' => 'Çelebi'),
			array('town_id' => '938','city_id' => '71','title' => 'Karakeçili'),
			array('town_id' => '939','city_id' => '71','title' => 'Yahşihan'),
			array('town_id' => '940','city_id' => '72','title' => 'Merkez'),
			array('town_id' => '941','city_id' => '72','title' => 'Beşiri'),
			array('town_id' => '942','city_id' => '72','title' => 'Gercüş'),
			array('town_id' => '943','city_id' => '72','title' => 'Kozluk'),
			array('town_id' => '944','city_id' => '72','title' => 'Sason'),
			array('town_id' => '945','city_id' => '72','title' => 'Hasankeyf'),
			array('town_id' => '946','city_id' => '73','title' => 'Beytüşşebap'),
			array('town_id' => '947','city_id' => '73','title' => 'Cizre'),
			array('town_id' => '948','city_id' => '73','title' => 'İdil'),
			array('town_id' => '949','city_id' => '73','title' => 'Silopi'),
			array('town_id' => '950','city_id' => '73','title' => 'Merkez'),
			array('town_id' => '951','city_id' => '73','title' => 'Uludere'),
			array('town_id' => '952','city_id' => '73','title' => 'Güçlükonak'),
			array('town_id' => '953','city_id' => '74','title' => 'Merkez'),
			array('town_id' => '954','city_id' => '74','title' => 'Kurucaşile'),
			array('town_id' => '955','city_id' => '74','title' => 'Ulus'),
			array('town_id' => '956','city_id' => '74','title' => 'Amasra'),
			array('town_id' => '957','city_id' => '75','title' => 'Merkez'),
			array('town_id' => '958','city_id' => '75','title' => 'Çıldır'),
			array('town_id' => '959','city_id' => '75','title' => 'Göle'),
			array('town_id' => '960','city_id' => '75','title' => 'Hanak'),
			array('town_id' => '961','city_id' => '75','title' => 'Posof'),
			array('town_id' => '962','city_id' => '75','title' => 'Damal'),
			array('town_id' => '963','city_id' => '76','title' => 'Aralık'),
			array('town_id' => '964','city_id' => '76','title' => 'Merkez'),
			array('town_id' => '965','city_id' => '76','title' => 'Tuzluca'),
			array('town_id' => '966','city_id' => '76','title' => 'Karakoyunlu'),
			array('town_id' => '967','city_id' => '77','title' => 'Merkez'),
			array('town_id' => '968','city_id' => '77','title' => 'Altınova'),
			array('town_id' => '969','city_id' => '77','title' => 'Armutlu'),
			array('town_id' => '970','city_id' => '77','title' => 'Çınarcık'),
			array('town_id' => '971','city_id' => '77','title' => 'Çiftlikköy'),
			array('town_id' => '972','city_id' => '77','title' => 'Termal'),
			array('town_id' => '973','city_id' => '78','title' => 'Eflani'),
			array('town_id' => '974','city_id' => '78','title' => 'Eskipazar'),
			array('town_id' => '975','city_id' => '78','title' => 'Merkez'),
			array('town_id' => '976','city_id' => '78','title' => 'Ovacık'),
			array('town_id' => '977','city_id' => '78','title' => 'Safranbolu'),
			array('town_id' => '978','city_id' => '78','title' => 'Yenice'),
			array('town_id' => '979','city_id' => '79','title' => 'Merkez'),
			array('town_id' => '980','city_id' => '79','title' => 'Elbeyli'),
			array('town_id' => '981','city_id' => '79','title' => 'Musabeyli'),
			array('town_id' => '982','city_id' => '79','title' => 'Polateli'),
			array('town_id' => '983','city_id' => '80','title' => 'Bahçe'),
			array('town_id' => '984','city_id' => '80','title' => 'Kadirli'),
			array('town_id' => '985','city_id' => '80','title' => 'Merkez'),
			array('town_id' => '986','city_id' => '80','title' => 'Düziçi'),
			array('town_id' => '987','city_id' => '80','title' => 'Hasanbeyli'),
			array('town_id' => '988','city_id' => '80','title' => 'Sumbas'),
			array('town_id' => '989','city_id' => '80','title' => 'Toprakkale'),
			array('town_id' => '990','city_id' => '81','title' => 'Akçakoca'),
			array('town_id' => '991','city_id' => '81','title' => 'Merkez'),
			array('town_id' => '992','city_id' => '81','title' => 'Yığılca'),
			array('town_id' => '993','city_id' => '81','title' => 'Cumayeri'),
			array('town_id' => '994','city_id' => '81','title' => 'Gölyaka'),
			array('town_id' => '995','city_id' => '81','title' => 'Çilimli'),
			array('town_id' => '996','city_id' => '81','title' => 'Gümüşova'),
			array('town_id' => '997','city_id' => '81','title' => 'Kaynaşlı'),
			array('town_id' => '998','city_id' => '59','title' => 'Kapaklı'),
			array('town_id' => '999','city_id' => '82','title' => 'Gazimağusa'),
			array('town_id' => '1000','city_id' => '82','title' => 'Girne'),
			array('town_id' => '1001','city_id' => '82','title' => 'Güzelyurt'),
			array('town_id' => '1002','city_id' => '82','title' => 'İskele'),
			array('town_id' => '1003','city_id' => '82','title' => 'Lefkoşa')
		  );
		  $this->db->insert_batch('town', $town);
	}
}